#' @title Append the genotype information from a profile into the associated
#' Profile GDS File
#'
#' @description This function append the genotype information from a specific
#' profile into the Profile GDS file. The genotype information is extracted
#' from a SNV file as generated by SNP-pileup or other tools.
#'
#' @param pRAIDS a \code{parametersRAIDS} an object with all the RAIDS
#' parameters
#'
#' @return The function returns a \code{parametersRAIDS} an object with all the RAIDS
#' parameters updated.
#'
#' @examples
#'
#' ## Current directory
#' dataDir <- file.path(tempdir())
#'
#' fileGDS <- file.path(system.file("extdata/tests", package="RAIDS"), "ex1_good_small_1KG.gds")
#'
#' ## Copy required file into current directory
#' file.copy(from=file.path(system.file("extdata/tests", package="RAIDS"),
#'                     "ex1.txt.gz"), to=dataDir)
#'
#' ## The data.frame containing the information about the study
#' ## The 3 mandatory columns: "study.id", "study.desc", "study.platform"
#' ## The entries should be strings, not factors (stringsAsFactors=FALSE)
#' studyDF <- data.frame(study.id = "MYDATA",
#'                         study.desc = "Description",
#'                         study.platform = "PLATFORM",
#'                         stringsAsFactors = FALSE)
#'
#' ## The data.frame containing the information about the samples
#' ## The entries should be strings, not factors (stringsAsFactors=FALSE)
#' samplePED <- data.frame(Name.ID=c("ex1", "ex2"),
#'                     Case.ID=c("Patient_h11", "Patient_h12"),
#'                     Diagnosis=rep("Cancer", 2),
#'                     Sample.Type=rep("Primary Tumor", 2),
#'                     Source=rep("Databank B", 2), stringsAsFactors=FALSE)
#' rownames(samplePED) <- samplePED$Name.ID
#'
#' pRAIDS <- RAIDS:::paramRAIDS(profileFile=file.path(dataDir, "ex1.txt.gz"),
#'     studyDF=studyDF,
#'     genoSource="snp-pileup",
#'     pedStudy=samplePED,
#'     pathProfileGDS=dataDir,
#'     fileReferenceGDS=fileGDS
#'     )
#'
#' ## Parse the coverage to the Profile GDS file
#' pRAIDS <- RAIDS:::generateProfileRawGDS2(pRAIDS=pRAIDS)
#'
#'
#' ## The Profile GDS file 'ex1.gds' has been created in the
#' ## specified directory
#' list.files(dataDir)
#'
#' ## Unlink Profile GDS file (created for demo purpose)
#' unlink(file.path(dataDir, "ex1.gds"))
#' unlink(file.path(dataDir, "ex1.txt.gz"))
#'
#'
#' @author Pascal Belleau, Astrid Deschênes and Alexander Krasnitz
#' @importFrom gdsfmt add.gdsn write.gdsn openfn.gds
#' @importFrom stats qbinom
#' @importFrom utils read.csv
#' @encoding UTF-8
#' @keywords internal
generateProfileRawGDS2 <- function(pRAIDS=pRAIDS) {


    if( is.null(pRAIDS$listPos)){
        gdsReference <- snpgdsOpen(filename=pRAIDS$fileReferenceGDS)
        snpChromosome <- read.gdsn(index.gdsn(gdsReference, "snp.chromosome"))
        keepPos <- seq_len(length(snpChromosome))
        if("snp.KeepDefault" %in% ls.gdsn(gdsReference) ){
            keepPos <- read.gdsn(index.gdsn(gdsReference, "snp.KeepDefault"))
        }

        if(pRAIDS$genoSource == "bam"){
            alDf <- read.gdsn(index.gdsn(gdsReference, "snp.allele"))[keepPos]
            alDf <- read.gdsn(index.gdsn(gdsReference, "snp.allele"))[keepPos]
            alDf <- matrix(unlist(strsplit(alDf,"\\/")),nrow=2)
            pRAIDS$listPos <- data.frame(snp.chromosome = snpChromosome[keepPos],
                                         snp.position = read.gdsn(index.gdsn(gdsReference, "snp.position"))[keepPos],
                                         REF = alDf[1,keepPos],
                                         ALT = alDf[2, keepPos],
                                         stringsAsFactors = FALSE
            )

            rm(alDf)
        } else{
            pRAIDS$listPos <- data.frame(snp.chromosome=snpChromosome[keepPos],
                                         snp.position=read.gdsn(index.gdsn(node=gdsReference, "snp.position"))[keepPos])
        }
        rm(snpChromosome, keepPos)
        #pRAIDS$listPos <- listPos
        closefn.gds(gdsReference)
    }
    # for(i in seq_len(length(listSamples))) {
    #pos <- which(listSampleFile == listSamples[i])

    if(pRAIDS$verbose) { message("generateProfileGDS start ", " ", Sys.time()) }

    #    if(length(pos) == 1) {

    #
    infoCov <- dispatchParseReadCov(pRAIDS=pRAIDS)
    matSample <- infoCov$matProfile
    pRAIDS <- infoCov$pRAIDS

    rm(infoCov)

    
    # matAll <- merge(matSample[,c( "Chromosome", "Position",
    #                               "File1R",  "File1A",
    #                               "count" )],
    #                 listPos,
    #                 by.x = c("Chromosome", "Position"),
    #                 by.y = c("snp.chromosome", "snp.position"),
    #                 all.y = TRUE,
    #                 all.x = FALSE)
    #
    # below same as the merge above but faster

    if(pRAIDS$verbose) { message("End read ", Sys.time()) }

    z <- cbind(c(pRAIDS$listPos$snp.chromosome, matSample$Chromosome,
                 matSample$Chromosome),
               c(pRAIDS$listPos$snp.position, matSample$Position,
                 matSample$Position),
               c(rep(1,nrow(pRAIDS$listPos)), rep(0,nrow(matSample)),
                 rep(2,nrow(matSample))),
               c(rep(0,nrow(pRAIDS$listPos)), matSample[, "File1R"],
                 -1 * matSample[, "File1R"]),
               c(rep(0,nrow(pRAIDS$listPos)), matSample[, "File1A"],
                 -1 * matSample[, "File1A"]),
               c(rep(0,nrow(pRAIDS$listPos)), matSample[, "count"],
                 -1 * matSample[, "count"]))
    rm(matSample)
    z <- z[order(z[,1], z[,2], z[,3]),]

    matAll <- data.frame(Chromosome=z[z[, 3] == 1, 1],
                         Position=z[z[, 3] == 1, 2], File1R=cumsum(z[, 4])[z[, 3] == 1],
                         File1A=cumsum(z[,5])[z[, 3] == 1],
                         count=cumsum(z[, 6])[z[, 3] == 1])
    rm(z)

    if(is.null(pRAIDS$pathProfileGDS)){
        stop("pathProfileGDS is NULL in ",
             "generateProfileGDS2\n")
    } else{
        if(!dir.exists(pRAIDS$pathProfileGDS)) { dir.create(pRAIDS$pathProfileGDS) }
    }
    fileGDSSample <- file.path(pRAIDS$pathProfileGDS, paste0(pRAIDS$pedStudy$Name.ID[1], ".gds"))
    gdsSample <- NULL
    if(file.exists(fileGDSSample)) {
        gdsSample <- openfn.gds(fileGDSSample, readonly=FALSE)
    } else{
        gdsSample <- createfn.gds(fileGDSSample)
    }

    if (! "Ref.count" %in% ls.gdsn(gdsSample)) {
        var.Ref <- add.gdsn(gdsSample, "Ref.count", matAll$File1R,
                            valdim=c( nrow(pRAIDS$listPos), 1), storage="sp.int16")
        var.Alt <- add.gdsn(gdsSample, "Alt.count", matAll$File1A,
                            valdim=c( nrow(pRAIDS$listPos), 1), storage="sp.int16")
        var.Count <- add.gdsn(gdsSample, "Total.count", matAll$count,
                              valdim=c( nrow(pRAIDS$listPos), 1), storage="sp.int16")
    } else {
        # you must append
        var.Ref <- append.gdsn(index.gdsn(gdsSample, "Ref.count"),
                               matAll$File1R)
        var.Alt <- append.gdsn(index.gdsn(gdsSample, "Alt.count"),
                               matAll$File1A)
        var.Count <- append.gdsn(index.gdsn(gdsSample, "Total.count"),
                                 matAll$count)
    }

    listSampleGDS <- addStudyGDSSample(gdsSample, pedProfile=pRAIDS$pedStudy,
                                       batch=pRAIDS$batch, listSamples=c(pRAIDS$pedStudy$Name.ID[1]), studyDF=pRAIDS$studyDF,
                                       verbose=pRAIDS$verbose)



    if (pRAIDS$verbose) { message("End Raw ", pRAIDS$pedStudy$Name.ID[1], " ",  Sys.time()) }
    closefn.gds(gdsfile=gdsSample)
    ## Success
    return(pRAIDS)
}


#' @title Append the genotype information from a profile into the associated
#' Profile GDS File
#'
#' @description This function append the genotype information from a specific
#' profile into the Profile GDS file. The genotype information is extracted
#' from a SNV file as generated by SNP-pileup or other tools.
#'
#' @param pRAIDS a \code{parametersRAIDS} an object with all the RAIDS
#' parameters
#'
#' @return The  function returns \code{0L} when successful.
#'
#' @examples
#'
#' ## Current directory
#' dataDir <- file.path(tempdir())
#'
#' fileGDS <- file.path(system.file("extdata/tests", package="RAIDS"), "ex1_good_small_1KG.gds")
#'
#' ## Copy required file into current directory
#' file.copy(from=file.path(system.file("extdata/tests", package="RAIDS"),
#'                     "ex1.txt.gz"), to=dataDir)
#'
#' ## The data.frame containing the information about the study
#' ## The 3 mandatory columns: "study.id", "study.desc", "study.platform"
#' ## The entries should be strings, not factors (stringsAsFactors=FALSE)
#' studyDF <- data.frame(study.id = "MYDATA",
#'                         study.desc = "Description",
#'                         study.platform = "PLATFORM",
#'                         stringsAsFactors = FALSE)
#'
#' ## The data.frame containing the information about the samples
#' ## The entries should be strings, not factors (stringsAsFactors=FALSE)
#' samplePED <- data.frame(Name.ID=c("ex1", "ex2"),
#'                     Case.ID=c("Patient_h11", "Patient_h12"),
#'                     Diagnosis=rep("Cancer", 2),
#'                     Sample.Type=rep("Primary Tumor", 2),
#'                     Source=rep("Databank B", 2), stringsAsFactors=FALSE)
#' rownames(samplePED) <- samplePED$Name.ID
#'
#' pRAIDS <- RAIDS:::paramRAIDS(profileFile=file.path(dataDir, "ex1.txt.gz"),
#'     studyDF=studyDF,
#'     genoSource="snp-pileup",
#'     pedStudy=samplePED,
#'     pathProfileGDS=dataDir,
#'     fileReferenceGDS=fileGDS
#'     )
#'
#' ## Parse the coverage to the Profile GDS file
#' pRAIDS <- RAIDS:::generateProfileRawGDS2(pRAIDS=pRAIDS)
#'
#'
#' ## The function returns OL when successful
#' result <- RAIDS:::generateProfileGenoCall(pRAIDS=pRAIDS)
#'
#' ## The Profile GDS file 'ex1.gds' has been created in the
#' ## specified directory
#' list.files(dataDir)
#'
#' ## Unlink Profile GDS file (created for demo purpose)
#' unlink(file.path(dataDir, "ex1.gds"))
#' unlink(file.path(dataDir, "ex1.txt.gz"))
#'
#'
#' @author Pascal Belleau, Astrid Deschênes and Alexander Krasnitz
#' @importFrom gdsfmt add.gdsn write.gdsn openfn.gds
#' @importFrom stats qbinom
#' @importFrom utils read.csv
#' @encoding UTF-8
#' @keywords internal
generateProfileGenoCall <- function(pRAIDS=pRAIDS) {


    fileGDSProfile <- file.path(pRAIDS$pathProfileGDS, paste0(pRAIDS$pedStudy$Name.ID[1], ".gds"))

    if(file.exists(fileGDSProfile)) {
        gdsProfile <- openfn.gds(fileGDSProfile, readonly=FALSE)
    }else{
        stop(paste("The file ", fileGDSProfile, "doesn't exists"))
    }

    if(pRAIDS$verbose) { message("generateProfileGDS start ", " ", Sys.time()) }

    z <- cbind(as.integer(read.gdsn(index.gdsn(gdsProfile, "Ref.count"))),
               as.integer(read.gdsn(index.gdsn(gdsProfile, "Alt.count"))),
               as.integer(read.gdsn(index.gdsn(gdsProfile, "Total.count"))))



    listCount <- table(z[,3][z[,3] >= pRAIDS$minCov])
    cutOffA <-
        data.frame(count=unlist(vapply(as.integer(names(listCount)),
                                       FUN=function(x, minProb, eProb){
                                           return(max(2,qbinom(minProb, x, eProb))) },
                                       FUN.VALUE=numeric(1),
                                       minProb=pRAIDS$minProb,
                                       eProb=2 * pRAIDS$seqError)),
                   allele=unlist(vapply(as.integer(names(listCount)),
                                        FUN=function(x, minProb, eProb){
                                            return(max(2,qbinom(minProb, x, eProb))) },
                                        FUN.VALUE=numeric(1),
                                        minProb=pRAIDS$minProb,
                                        eProb=pRAIDS$seqError)))

    row.names(cutOffA) <- names(listCount)
    # Initialize the genotype array at -1

    # Select the position where the coverage of the 2 alleles is enough
    listCov <- which(rowSums(z[, seq_len(2)]) >= pRAIDS$minCov)

    zC <- z[listCov,]

    # The difference  depth - (nb Ref + nb Alt) can be realistically
    # explain by sequencing error
    listCov <- listCov[(zC[,3] -
                            (zC[,1] + zC[,2])) <
                           cutOffA[as.character(zC[,3]), "count"]]
    zC <- z[listCov,]
    #matAllC <- matAll[listCov,]
    #rm(matAll)

    g <- as.matrix(rep(-1, nrow(pRAIDS$listPos)))
    # The sample is homozygote if the other known allele have a
    # coverage of 0

    g[listCov][which(zC[,2] == 0)] <- 0
    g[listCov][which(zC[,1] == 0)] <- 2

    # The sample is heterozygote if explain the coverage of
    # the minor allele by sequencing error is not realistic.
    g[listCov][which(zC[,2] >=
                         cutOffA[as.character(zC[,3]), "allele"] &
                         zC[,1] >= cutOffA[as.character(zC[,3]),
                                                   "allele"])] <- 1

    #g <- as.matrix(g)
    if("geno.ref" %in% ls.gdsn(gdsProfile)){
        var.geno <- index.gdsn(gdsProfile, pRAIDS$genoType)

        compression.gdsn(var.geno, compress="")
        append.gdsn(var.geno, g, check=TRUE)
        compression.gdsn(var.geno, compress="LZMA_RA.fast")
        readmode.gdsn(var.geno)

    }else{
        var.geno <- add.gdsn(gdsProfile, pRAIDS$genoType, valdim=c(length(g), 1),
                             g, storage="bit2", compress = "LZMA_RA.fast")
        readmode.gdsn(var.geno)
    }

    rm(g)
    closefn.gds(gdsfile=gdsProfile)

    if (pRAIDS$verbose) { message("End ", pRAIDS$pedStudy$Name.ID[1], " ",  Sys.time()) }

    ## Success
    return(0L)
}


#' @title Add the genotype information for the list of pruned SNVs
#' into the Profile GDS file
#'
#' @description The function extracts the information about the pruned SNVs
#' from the 1KG GDS file and adds entries related to the pruned SNVs in
#' the Profile GDS file. The nodes are added to the Profile GDS file:
#' 'sample.id', 'snp.id', 'snp.chromosome', 'snp.position', 'snp.index',
#' 'genotype' and 'lap'.
#'
#' @param pRAIDS a \code{parametersRAIDS} an object with all the RAIDS
#' parameters
#'
#' @return The function returns \code{0L} when successful.
#'
#' @examples
#'
#' ## Required library for GDS
#' library(gdsfmt)
#'
#' ## Path to the demo Reference GDS file is located in this package
#' dataDir <- system.file("extdata/tests", package="RAIDS")
#' fileGDS <- file.path(dataDir, "ex1_good_small_1KG.gds")
#'
#' ## The data.frame containing the information about the study
#' ## The 3 mandatory columns: "study.id", "study.desc", "study.platform"
#' ## The entries should be strings, not factors (stringsAsFactors=FALSE)
#' studyDF <- data.frame(study.id = "MYDATA",
#'                         study.desc = "Description",
#'                         study.platform = "PLATFORM",
#'                         stringsAsFactors = FALSE)
#'
#' ## The data.frame containing the information about the samples
#' ## The entries should be strings, not factors (stringsAsFactors=FALSE)
#' samplePED <- data.frame(Name.ID = c("ex1", "ex2"),
#'                     Case.ID = c("Patient_h11", "Patient_h12"),
#'                     Diagnosis = rep("Cancer", 2),
#'                     Sample.Type = rep("Primary Tumor", 2),
#'                     Source = rep("Databank B", 2), stringsAsFactors = FALSE)
#' rownames(samplePED) <- samplePED$Name.ID
#'
#' ## Temporary Profile GDS file
#' pathProfileGDS <- tempdir()
#' profileFile <- file.path(pathProfileGDS, "ex1.gds")
#'
#' pRAIDS <- RAIDS:::paramRAIDS(profileFile=file.path(dataDir, "ex1.txt.gz"),
#'     studyDF=studyDF,
#'     genoSource="snp-pileup",
#'     pedStudy=samplePED,
#'     pathProfileGDS=pathProfileGDS,
#'     fileReferenceGDS=fileGDS
#'     )
#' ## Copy the Profile GDS file demo that has not been pruned yet
#' file.copy(file.path(dataDir, "ex1_demo.gds"), profileFile)
#'
#'
#' ## Compute the list of pruned SNVs for a specific profile 'ex1'
#' ## and save it in the Profile GDS file 'ex1.gds'
#' pRAIDS <- pruningProfile2(pRAIDS)
#' RAIDS::addGenotypeProfile(pRAIDS)
#' 
#' content <- openfn.gds(profileFile)
#' content
#'
#' ## Close the Profile GDS file (important)
#' closefn.gds(content)
#'
#' ## Remove Profile GDS file (created for demo purpose)
#' unlink(profileFile, force=TRUE)
#'
#'
#' @author Pascal Belleau, Astrid Deschênes and Alexander Krasnitz
#' @importFrom gdsfmt index.gdsn read.gdsn objdesp.gdsn openfn.gds closefn.gds
#' @importFrom SNPRelate snpgdsOpen
#' @encoding UTF-8
#' @export
addGenotypeProfile <- function(pRAIDS=pRAIDS) {

    ## Validate inputs
    # validateAdd1KG2SampleGDS(gdsReference=gdsReference,
    #                          gdsProfileFile=fileProfileGDS, currentProfile=currentProfile,
    #                          studyID=studyID)
    ## Profile GDS file name
    fileProfileGDS <-  validateProfileGDSExist(pathProfile=pRAIDS$pathProfileGDS,
                                    profile=pRAIDS$pedStudy$Name.ID[1])
    ## Open Profile GDS file
    gdsProfile <- openfn.gds(fileProfileGDS, readonly=FALSE)
    if(! ("pruned.study" %in% ls.gdsn(gdsProfile))){
        closefn.gds(gdsProfile)
        stop(paste0("Call addGenotypeProfileGDS without pruned.study\n"))
    }

    gdsReference <- snpgdsOpen(filename=pRAIDS$fileReferenceGDS)

    ## Extract needed information from 1KG GDS file
    snp.id <- read.gdsn(index.gdsn(gdsReference, "snp.id"))

    ## Extract list of pruned SNVs from the GDS Sample file
    pruned <- read.gdsn(index.gdsn(gdsProfile, "pruned.study"))

    listSNP <- which(snp.id %in% pruned)

    snp.chromosome <- read.gdsn(index.gdsn(gdsReference,
                                                "snp.chromosome"))[listSNP]
    snp.position <-  read.gdsn(index.gdsn(gdsReference,
                                                "snp.position"))[listSNP]

    add.gdsn(gdsProfile, "sample.id", c(pRAIDS$pedStudy$Name.ID[1]))

    add.gdsn(gdsProfile, "snp.id", snp.id[listSNP])
    add.gdsn(gdsProfile, "snp.chromosome", snp.chromosome)
    add.gdsn(gdsProfile, "snp.position", snp.position)
    # snp.index is the index of the snp pruned in snp.id from 1KG gds
    add.gdsn(gdsProfile, "snp.index", listSNP)

    study.annot <- read.gdsn(index.gdsn(gdsProfile, "study.annot"))

    posCur <- which(study.annot$data.id == pRAIDS$pedStudy$Name.ID[1] &
                        study.annot$study.id == pRAIDS$studyDF$study.id[1])


    g <- read.gdsn(index.gdsn(gdsProfile, pRAIDS$genoType), start=c(1, posCur),
                                    count=c(-1, 1))[listSNP]
    if(! ("genotype" %in% ls.gdsn(gdsProfile))){
        var.geno <- add.gdsn(gdsProfile, "genotype",
                        valdim=c(length(listSNP), 1), g, storage="bit2")
    }else {
        if(is.null(var.geno)){
            var.geno <- index.gdsn(gdsProfile, "genotype")
        }
        append.gdsn(var.geno, g)
    }

    add.gdsn(gdsProfile, "lap",
             rep(0.5, objdesp.gdsn(index.gdsn(gdsProfile, "genotype"))$dim[1]),
             storage="packedreal8")

    ## Close the GDS Sample file
    closefn.gds(gdsProfile)
    closefn.gds(gdsReference)

    return(0L)
}




